# Generated by Django 5.2.14 on 2026-05-29 19:26

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('tema', models.CharField(blank=True, help_text='Tema relacionado con el material.', max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('imagen', 'Imagen'), ('texto', 'Texto manual'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=documentos.models.ruta_material_usuario)),
                ('texto_manual', models.TextField(blank=True, help_text='Texto escrito directamente por el estudiante.')),
                ('texto_extraido', models.TextField(blank=True, help_text='Texto extraído del archivo o copiado desde el texto manual.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_estudio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material de estudio',
                'verbose_name_plural': 'Materiales de estudio',
                'ordering': ['-creado'],
            },
        ),
    ]
