# Generated by Django 5.2.14 on 2026-05-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialestudio',
            name='error_procesamiento',
            field=models.TextField(blank=True, help_text='Mensaje de error si el procesamiento falla.'),
        ),
        migrations.AddField(
            model_name='materialestudio',
            name='preguntas_sugeridas_ia',
            field=models.TextField(blank=True, help_text='Preguntas sugeridas por Gemini.'),
        ),
        migrations.AddField(
            model_name='materialestudio',
            name='recomendacion_ia',
            field=models.TextField(blank=True, help_text='Recomendación generada por Gemini.'),
        ),
        migrations.AddField(
            model_name='materialestudio',
            name='resumen_ia',
            field=models.TextField(blank=True, help_text='Resumen generado por Gemini.'),
        ),
        migrations.AddField(
            model_name='materialestudio',
            name='temas_clave_ia',
            field=models.TextField(blank=True, help_text='Temas clave detectados por Gemini.'),
        ),
        migrations.AlterField(
            model_name='materialestudio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
    ]
