# Generated by Django 5.2.14 on 2026-05-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_materialestudio_error_procesamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialestudio',
            name='temario_examen',
            field=models.TextField(blank=True, default='', help_text='Temas específicos que entrarán al examen.'),
        ),
        migrations.AlterField(
            model_name='materialestudio',
            name='tema',
            field=models.CharField(blank=True, help_text='Tema general relacionado con el material.', max_length=180),
        ),
        migrations.AlterField(
            model_name='materialestudio',
            name='texto_extraido',
            field=models.TextField(blank=True, help_text='Texto extraído del archivo.'),
        ),
        migrations.AlterField(
            model_name='materialestudio',
            name='texto_manual',
            field=models.TextField(blank=True, help_text='Campo conservado para materiales antiguos.'),
        ),
    ]
