# Generated by Django 5.2.14 on 2026-05-30 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Simulacro de Anatomía I', max_length=220)),
                ('instrucciones', models.TextField(blank=True)),
                ('dificultad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20)),
                ('cantidad_preguntas', models.PositiveIntegerField(default=10)),
                ('preguntas_json', models.JSONField(blank=True, default=list, help_text='Preguntas generadas por Gemini.')),
                ('respuestas_json', models.JSONField(blank=True, default=dict, help_text='Respuestas del estudiante y corrección.')),
                ('puntaje', models.PositiveIntegerField(default=0)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('retroalimentacion_ia', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('respondido', 'Respondido')], default='generado', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes', to='rutas.rutaaprendizaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen generado',
                'verbose_name_plural': 'Exámenes generados',
                'ordering': ['-creado'],
            },
        ),
    ]
