# Generated by Django 5.2.14 on 2026-05-30 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0003_materialestudio_temario_examen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Ruta de aprendizaje personalizada', max_length=200)),
                ('resumen_general', models.TextField(blank=True)),
                ('estilo_vark_usado', models.CharField(blank=True, max_length=80)),
                ('dias_hasta_examen', models.PositiveIntegerField(default=0)),
                ('dias_planificados', models.PositiveIntegerField(default=0)),
                ('minutos_por_dia', models.PositiveIntegerField(default=60)),
                ('temas_priorizados', models.TextField(blank=True, help_text='Temas priorizados por Gemini.')),
                ('plan_json', models.JSONField(blank=True, default=list, help_text='Plan diario generado por Gemini.')),
                ('recomendaciones_finales', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('materiales', models.ManyToManyField(blank=True, related_name='rutas_aprendizaje', to='documentos.materialestudio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_aprendizaje', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta de aprendizaje',
                'verbose_name_plural': 'Rutas de aprendizaje',
            },
        ),
    ]
