# Generated by Django 5.2.14 on 2026-05-29 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilVARK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_visual', models.PositiveIntegerField(default=0)),
                ('puntaje_auditivo', models.PositiveIntegerField(default=0)),
                ('puntaje_lectura', models.PositiveIntegerField(default=0)),
                ('puntaje_kinestesico', models.PositiveIntegerField(default=0)),
                ('estilo_principal', models.CharField(choices=[('visual', 'Visual'), ('auditivo', 'Auditivo'), ('lectura', 'Lectura/Escritura'), ('kinestesico', 'Kinestésico')], default='visual', max_length=20)),
                ('fecha_realizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vark', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil VARK',
                'verbose_name_plural': 'Perfiles VARK',
            },
        ),
    ]
