# Generated by Django 5.2.14 on 2026-05-29 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(default='Anatomía I', max_length=120)),
                ('tema_actual', models.CharField(help_text='Ejemplo: Sistema óseo, cráneo, músculos del miembro superior.', max_length=180)),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha desde la que empezará a estudiar.', null=True)),
                ('fecha_examen', models.DateField(help_text='Fecha del próximo examen.')),
                ('horas_por_dia', models.DecimalField(decimal_places=1, help_text='Horas disponibles para estudiar por día.', max_digits=4)),
                ('tipo_examen', models.CharField(choices=[('opcion_multiple', 'Opción múltiple'), ('oral', 'Oral'), ('escrito', 'Escrito'), ('practico', 'Práctico'), ('mixto', 'Mixto')], default='mixto', max_length=30)),
                ('nivel_dificultad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('muy_alta', 'Muy alta')], default='media', max_length=20)),
                ('temas_dificiles', models.TextField(blank=True, help_text='Temas que más le cuestan al estudiante.')),
                ('objetivo_estudio', models.TextField(blank=True, help_text='Meta del estudiante para este periodo de estudio.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_academicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos académicos',
                'verbose_name_plural': 'Datos académicos',
            },
        ),
    ]
