# Generated by Django 5.2.14 on 2026-05-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anatomia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosacademicos',
            name='horas_por_dia',
        ),
        migrations.AddField(
            model_name='datosacademicos',
            name='minutos_por_dia',
            field=models.PositiveIntegerField(default=60, help_text='Minutos disponibles para estudiar por día.'),
        ),
    ]
